// import Image from "next/image";
import React from 'react';
import { t } from "@/lib/utils"
import { getDictionary } from "@/i18n/get-dictionary"
import { Locale } from '@/i18n/settings';
import { Metadata } from 'next';
import TitleWithImageCard from '@/components/TitleWithImageCard';
import { FileSearchOutlined, FolderOpenOutlined, MoreOutlined, PoweroffOutlined, ReadOutlined, ReconciliationOutlined } from '@ant-design/icons';
import WellcomeCard from "@/components/WellcomeCard"
import routes from '@/routes';

export const metadata: Metadata = {
  title: "صفحه مدیریت",
  // description: "Generated by create next app",
};

export default async function Home(
  {
    params
  }: {
    params: Promise<{ lang: Locale }>,
  }) {
  const { lang } = (await params)
  const dict = await getDictionary(lang)

  
  return (
    <div className="App">
      <WellcomeCard locale={lang} />

      {[{ icon: <ReadOutlined />, title: t(dict.common.latestSentEntities, dict.common.docs), bgColor: 'var(--primary-color)', url: routes.docsList },
      { icon: <FolderOpenOutlined />, title: t(dict.common.events), bgColor: 'var(--secondary-color)', url: routes.eventList },
      { icon: <FileSearchOutlined />, title: t(dict.common.search), bgColor: 'var(--card-color3)', url: routes.search},
      { icon: <ReconciliationOutlined />, title: t(dict.common.report),  bgColor: 'var(--card-color4)', url: routes.getReports },
      { icon: <MoreOutlined />, title: t(dict.common.otherOptions), bgColor: 'var(--card-color5)', url: routes.otherFeatures },
      { icon: <PoweroffOutlined />, title: t(dict.common.exit), bgColor: 'var(--danger-color)', url: routes.logout }].map(({ icon, title, bgColor, url }, index) => (
          <TitleWithImageCard icon={icon} key={index} title={title} linkTitle={title} bgColor={bgColor} href={url} />
      ))}

    </div>
  )
}