import type { Metadata } from "next";
// import "./globals.css";
import { Locale } from '@/i18n/settings'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ lang: Locale }>
}>) {
  const lang = (await params).lang
  return (
    <html lang={lang}>
      <body>
        {children}
      </body>
    </html>
  );
}
